---
- name: Restart isc-dhcp-server
  ansible.builtin.service:
    name: isc-dhcp-server
    state: restarted

- name: Restart nfs-kernel-server
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted

- name: Restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted
